"""baseline schema

Revision ID: 1bfacee578a4
Revises:
Create Date: 2026-07-13 12:44:20.390479

Autogenerated from app/services/omnichannel/models.py against a real local
Postgres 16 (verified by actually running upgrade/downgrade, not just
generating this file -- see docs/omnichannel-decisions.md for how it was
checked). The ``omnichannel`` schema itself is created by
migrations/env.py before this migration runs, so table creation below can
assume the schema already exists.

One thing autogenerate cannot detect: the full-text GIN index on
``messages.body_text`` (CLAUDE.md §5.1) is a functional index over
``to_tsvector(...)``, which has no SQLAlchemy ORM column representation --
it's added by hand at the end of ``upgrade()``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1bfacee578a4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("channel_type", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("provider_account_id", sa.Text(), nullable=False),
        sa.Column("credentials_secret_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_channel_connections_org_id"),
        "channel_connections",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "channel_identities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("channel_type", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("customer_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "channel_type", "external_id", name="uq_channel_identity"),
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_channel_identities_org_id"),
        "channel_identities",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "commission_rules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_commission_rules_org_id"),
        "commission_rules",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "presence",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", name="uq_presence_org_user"),
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_presence_org_id"),
        "presence",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("channel_type", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_template_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_templates_org_id"),
        "templates",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("customer_identity_id", sa.String(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("assigned_user_id", sa.String(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_preview", sa.Text(), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_identity_id"],
            ["omnichannel.channel_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omnichannel",
    )
    op.create_index(
        "ix_conversations_agent_inbox",
        "conversations",
        ["org_id", "assigned_user_id", "status"],
        unique=False,
        schema="omnichannel",
    )
    op.create_index(
        "ix_conversations_inbox",
        "conversations",
        ["org_id", "status", "last_message_at"],
        unique=False,
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_conversations_org_id"),
        "conversations",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "commission_attributions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("agent_user_id", sa.String(), nullable=False),
        sa.Column("rule_snapshot", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["omnichannel.conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omnichannel",
    )
    op.create_index(
        "ix_commission_attributions_dashboard",
        "commission_attributions",
        ["org_id", "agent_user_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_commission_attributions_org_id"),
        "commission_attributions",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "conversation_assignments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("assigned_user_id", sa.String(), nullable=False),
        sa.Column("assigned_by", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["omnichannel.conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_conversation_assignments_conversation_id"),
        "conversation_assignments",
        ["conversation_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_conversation_assignments_org_id"),
        "conversation_assignments",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("channel_type", sa.Text(), nullable=False),
        sa.Column("external_message_id", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("sent_by_user_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["omnichannel.conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_type", "external_message_id", name="uq_message_idempotency"),
        schema="omnichannel",
    )
    op.create_index(
        "ix_messages_thread",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_messages_org_id"),
        "messages",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_table(
        "message_attachments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["omnichannel.messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_message_attachments_message_id"),
        "message_attachments",
        ["message_id"],
        unique=False,
        schema="omnichannel",
    )
    op.create_index(
        op.f("ix_omnichannel_message_attachments_org_id"),
        "message_attachments",
        ["org_id"],
        unique=False,
        schema="omnichannel",
    )
    # ### end Alembic commands ###

    # Hand-written: full-text GIN index (§5.1) -- not representable as an ORM column.
    op.execute(
        "CREATE INDEX ix_messages_fulltext ON omnichannel.messages "
        "USING gin (to_tsvector('english', coalesce(body_text, '')))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS omnichannel.ix_messages_fulltext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_omnichannel_message_attachments_org_id"),
        table_name="message_attachments",
        schema="omnichannel",
    )
    op.drop_index(
        op.f("ix_omnichannel_message_attachments_message_id"),
        table_name="message_attachments",
        schema="omnichannel",
    )
    op.drop_table("message_attachments", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_messages_org_id"), table_name="messages", schema="omnichannel"
    )
    op.drop_index("ix_messages_thread", table_name="messages", schema="omnichannel")
    op.drop_table("messages", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_conversation_assignments_org_id"),
        table_name="conversation_assignments",
        schema="omnichannel",
    )
    op.drop_index(
        op.f("ix_omnichannel_conversation_assignments_conversation_id"),
        table_name="conversation_assignments",
        schema="omnichannel",
    )
    op.drop_table("conversation_assignments", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_commission_attributions_org_id"),
        table_name="commission_attributions",
        schema="omnichannel",
    )
    op.drop_index(
        "ix_commission_attributions_dashboard",
        table_name="commission_attributions",
        schema="omnichannel",
    )
    op.drop_table("commission_attributions", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_conversations_org_id"),
        table_name="conversations",
        schema="omnichannel",
    )
    op.drop_index("ix_conversations_inbox", table_name="conversations", schema="omnichannel")
    op.drop_index("ix_conversations_agent_inbox", table_name="conversations", schema="omnichannel")
    op.drop_table("conversations", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_templates_org_id"), table_name="templates", schema="omnichannel"
    )
    op.drop_table("templates", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_presence_org_id"), table_name="presence", schema="omnichannel"
    )
    op.drop_table("presence", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_commission_rules_org_id"),
        table_name="commission_rules",
        schema="omnichannel",
    )
    op.drop_table("commission_rules", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_channel_identities_org_id"),
        table_name="channel_identities",
        schema="omnichannel",
    )
    op.drop_table("channel_identities", schema="omnichannel")
    op.drop_index(
        op.f("ix_omnichannel_channel_connections_org_id"),
        table_name="channel_connections",
        schema="omnichannel",
    )
    op.drop_table("channel_connections", schema="omnichannel")
    # ### end Alembic commands ###
