"""baseline schema

Revision ID: 310e8122e78e
Revises:
Create Date: 2026-07-23 16:40:45.951462
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "310e8122e78e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("invoice_number", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("customer_email", sa.Text(), nullable=False),
        sa.Column("customer_name", sa.Text(), nullable=False),
        sa.Column("customer_company", sa.Text(), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("payment_terms", sa.Text(), nullable=True),
        sa.Column("subtotal_cents", sa.BigInteger(), nullable=False),
        sa.Column("tax_cents", sa.BigInteger(), nullable=False),
        sa.Column("discount_cents", sa.BigInteger(), nullable=False),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column("amount_paid_cents", sa.BigInteger(), nullable=False),
        sa.Column("payment_status", sa.Text(), nullable=False),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("pdf_s3_key", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "invoice_number", name="uq_invoice_number"),
        schema="invoicing",
    )
    op.create_index(
        "ix_invoices_org_created",
        "invoices",
        ["org_id", "created_at"],
        unique=False,
        schema="invoicing",
    )
    op.create_index(
        "ix_invoices_org_due_date",
        "invoices",
        ["org_id", "due_date"],
        unique=False,
        schema="invoicing",
    )
    op.create_index(
        "ix_invoices_org_status", "invoices", ["org_id", "status"], unique=False, schema="invoicing"
    )
    op.create_index(
        op.f("ix_invoicing_invoices_org_id"),
        "invoices",
        ["org_id"],
        unique=False,
        schema="invoicing",
    )
    op.create_table(
        "invoice_line_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_price_cents", sa.BigInteger(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoicing.invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="invoicing",
    )
    op.create_index(
        op.f("ix_invoicing_invoice_line_items_org_id"),
        "invoice_line_items",
        ["org_id"],
        unique=False,
        schema="invoicing",
    )
    op.create_index(
        "ix_line_items_org_invoice",
        "invoice_line_items",
        ["org_id", "invoice_id"],
        unique=False,
        schema="invoicing",
    )
    op.create_table(
        "invoice_payments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.Text(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("recorded_by", sa.String(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoicing.invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="invoicing",
    )
    op.create_index(
        op.f("ix_invoicing_invoice_payments_org_id"),
        "invoice_payments",
        ["org_id"],
        unique=False,
        schema="invoicing",
    )
    op.create_index(
        "ix_payments_org_invoice",
        "invoice_payments",
        ["org_id", "invoice_id"],
        unique=False,
        schema="invoicing",
    )
    op.create_index(
        "uq_payments_org_idempotency_key",
        "invoice_payments",
        ["org_id", "idempotency_key"],
        unique=True,
        schema="invoicing",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_payments_org_idempotency_key",
        table_name="invoice_payments",
        schema="invoicing",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_payments_org_invoice", table_name="invoice_payments", schema="invoicing")
    op.drop_index(
        op.f("ix_invoicing_invoice_payments_org_id"),
        table_name="invoice_payments",
        schema="invoicing",
    )
    op.drop_table("invoice_payments", schema="invoicing")
    op.drop_index("ix_line_items_org_invoice", table_name="invoice_line_items", schema="invoicing")
    op.drop_index(
        op.f("ix_invoicing_invoice_line_items_org_id"),
        table_name="invoice_line_items",
        schema="invoicing",
    )
    op.drop_table("invoice_line_items", schema="invoicing")
    op.drop_index(op.f("ix_invoicing_invoices_org_id"), table_name="invoices", schema="invoicing")
    op.drop_index("ix_invoices_org_status", table_name="invoices", schema="invoicing")
    op.drop_index("ix_invoices_org_due_date", table_name="invoices", schema="invoicing")
    op.drop_index("ix_invoices_org_created", table_name="invoices", schema="invoicing")
    op.drop_table("invoices", schema="invoicing")
    # ### end Alembic commands ###
